import dotenv from "dotenv";

dotenv.config({
  path: "./.env",
});

const PORT = process.env.PORT;
const CORS_ORIGIN = process.env.CORS_ORIGIN;
const MONGODB_URL = process.env.MONGODB_URL;

const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_SECRECT = process.env.CLOUDINARY_SECRECT;

const JWT_ACCESS_TOKEN_SECRET = process.env.JWT_ACCESS_TOKEN_SECRET;
const JWT_ACCESS_TOKEN_EXPIRE_IN = process.env.JWT_ACCESS_TOKEN_EXPIRE_IN;
const JWT_REFRESH_TOKEN_SECRET = process.env.JWT_REFRESH_TOKEN_SECRET;
const JWT_REFRESH_TOKEN_EXPIRE_IN = process.env.JWT_REFRESH_TOKEN_EXPIRE_IN;

export {
  PORT,
  CORS_ORIGIN,
  MONGODB_URL,
  CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_SECRECT,
  JWT_ACCESS_TOKEN_EXPIRE_IN,
  JWT_ACCESS_TOKEN_SECRET,
  JWT_REFRESH_TOKEN_EXPIRE_IN,
  JWT_REFRESH_TOKEN_SECRET
};
